os:
    - linux

serices:
    - docker

language: node_js
node_js:
    - "lts/*"

addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable

cache:
    npm: true
    directories:
        - $HOME/.npm
        - node_modules

before_install:
    - export CHROME_BIN=/usr/bin/google-chrome
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:
    - npm install

script:
    - npm run test

notifications:
    webhooks:
        on_success: change
        on_failure: always
        on_start: false
